# .github/workflows/deploy_frontend.yml

name: Deploy HaqooqAI Frontend to GitHub Pages

on:
  push:
    branches:
      - frontend
    paths:
      - 'frontend/HaqooqAI-frontend/**'
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clear npm cache
        working-directory: ./frontend/HaqooqAI-frontend
        run: npm cache clean --force

      - name: Install Frontend Dependencies
        working-directory: ./frontend/HaqooqAI-frontend
        # run: npm ci --no-audit --prefer-offline
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm ci --no-audit --prefer-offline

      - name: Build Frontend
        working-directory: ./frontend/HaqooqAI-frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/HaqooqAI-frontend/dist

